---
- name: Config Deb11
  hosts: all
  become: true
  vars_files:
    - secrets.yml

  tasks:
    - name: Set timezone +0 (UTC)
      ansible.builtin.timezone:
        name: Etc/UTC
    - name: Remove user debian
      ansible.builtin.user:
        name: debian
        state: absent
        remove: true
    - name: update apt cache
      ansible.builtin.apt:
        update_cache: true
    - name: Install list of packages
      ansible.builtin.apt:
        pkg:
          - libfreetype6
          - libfreetype6-dev
          - zlib1g
          - zlib1g-dev
          - libxml2
          - libxml2-dev
          - libxslt1-dev
          - libxslt1.1
          - gcc
          - curl
          - make
          - libcurl4-openssl-dev
          - libssl-dev
          - mc
          - wget
          - aptitude
          - unzip
          - htop
          - nload
          - libffi-dev
          - libmariadb-dev
          - default-libmysqlclient-dev
          - mariadb-client
          - gnupg2
          - pkg-config
          - tcl
          - git
          - sendmail
          - openssl
          - python3
          - python3-pip
          - python-setuptools
          - screen
          - ethtool
          - openssl
          - nodejs
          - npm
        state: latest
        update_cache: true
    - name: install nginx latest version
      ansible.builtin.apt:
        name: nginx
        state: latest
    - name: install reqired depend for mysql
      ansible.builtin.apt:
        name:
          - debconf-utils
        state: present
        update_cache: true
    - name: download config package mysql
      ansible.builtin.command: >
        curl -L -o /tmp/mysql-apt-config.deb
        https://dev.mysql.com/get/mysql-apt-config_0.8.28-1_all.deb
      args:
        creates: /tmp/mysql-apt-config.deb
    - name: configure mysql repo
      ansible.builtin.shell: |
        echo "mysql-apt-config mysql-apt-config/select-server select mysql-5.7" | debconf-set-selections
        echo "mysql-apt-config mysql-apt-config/select-product select Ok" | debconf-set-selections
        DEBIAN_FRONTEND=noninteractive dpkg -i /tmp/mysql-apt-config.deb
      args:
        executable: /bin/bash
    - name: set mysql root password
      ansible.builtin.debconf:
        name: mysql-server
        question: mysql-server/root_password
        value: "{{ mysql_root_password }}"
        vtype: password
    - name: confirm mysql root password
      ansible.builtin.debconf:
        name: mysql-server
        question: mysql-server/root_password_again
        value: "{{ mysql_root_password }}"
        vtype: password
    - name: install mysql 5.7 server and client
      ansible.builtin.apt:
        name:
          - mysql-server
          - mysql-client
        state: present
      environment:
        DEBIAN_FRONTEND: noninteractive
    - name: check mysql sevice
      ansible.builtin.systemd:
        name: mysql
        state: started
        enabled: true
    - name: test mysql connect
      ansible.builtin.shell: |
        mysql -u root -p"{{ mysql_root_password }}" -e "SELECT VERSION():"
      args:
        executable: /bin/bash
      register: mysql_test
      changed_when: false
    - name: succes message
      ansible.builtin.debug:
        msg: "✅ MySQL {{ mysql_test.stdout }} installed successfull!!"
    - name: clean up tmp file
      ansible.builtin.file:
        path: /tmp/mysql-apt-config.deb
        state: absent
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
    - name: install build py depend
      ansible.builtin.apt:
        name:
          - build-essential
          - wget
          - libssl-dev
          - zlib1g-dev
          - libbz2-dev
          - libreadline-dev
          - libsqlite3-dev
          - libffi-dev
          - libncurses5-dev
          - libgdbm-dev
          - liblzma-dev
          - tk-dev
          - libcurl4-openssl-dev
          - default-libmysqlclient-dev
          - pkg-config
          - ca-certificates
        state: present
    - name: Ensure source directory exists
      ansible.builtin.file:
        path: /usr/local/src
        state: directory
        mode: "0755"
    - name: Download Python 3.9.6 source
      ansible.builtin.get_url:
        url: https://www.python.org/ftp/python/3.9.6/Python-3.9.6.tgz
        dest: /usr/local/src/Python-3.9.6.tgz
        mode: "0644"
        use_proxy: false
        timeout: 120
    - name: Extract Python source
      ansible.builtin.unarchive:
        src: /usr/local/src/Python-3.9.6.tgz
        dest: /usr/local/src/
        remote_src: true
    - name: Configure Py
      ansible.builtin.command:
        cmd: ./configure --prefix=/opt/python3
        chdir: /usr/local/src/Python-3.9.6
      args:
        creates: /usr/local/src/Python-3.9.6/Makefile
    - name: Build Python
      ansible.builtin.command:
        cmd: make -j 2
        chdir: /usr/local/src/Python-3.9.6
      args:
        creates: /usr/local/src/Python-3.9.6/python
    - name: Install Python
      ansible.builtin.command:
        cmd: make install
        chdir: /usr/local/src/Python-3.9.6
      args:
        creates: /opt/python3/bin/python3.9
    - name: install PHP prereq
      ansible.builtin.apt:
        name:
          - php
          - php-cli
          - php-curl
          - php-zip
          - php-xml
          - php-json
          - php-mbstring
          - curl
        state: present
        update_cache: true
    - name: Check  Composer is already
      ansible.builtin.stat:
        path: /usr/local/bin/composer
      register: composer_binary
    - name: Download latest Composer installer
      ansible.builtin.get_url:
        url: https://getcomposer.org/installer
        dest: /tmp/composer-setup.php
      when: not composer_binary.stat.exists
    - name: Install Composer if not exist
      ansible.builtin.command: >
        php /tmp/composer-setup.php
        --install-dir=/usr/local/bin
        --filename=composer
      when: not composer_binary.stat.exists
    - name: Clean up installer
      ansible.builtin.file:
        path: /tmp/composer-setup.php
        state: absent
      when: not composer_binary.stat.exists
    - name: Set permissions
      ansible.builtin.file:
        path: /usr/local/bin/composer
        mode: '0755'
        owner: root
        group: root
    - name: verify new Composer version
      ansible.builtin.command: composer --version
      register: new_composer_version
      changed_when: false
    - name: set net.ipv4.ip_local_port_range
      ansible.builtin.sysctl:
        name: net.ipv4.ip_local_port_range
        value: "1024 65535"
        state: present
        sysctl_file: /etc/sysctl.d/99-custom.conf
        reload: false
        ignoreerrors: true
      register: net_param_result
    - name: Set fs.nr_open
      ansible.builtin.sysctl:
        name: fs.nr_open
        value: "2000000"
        state: present
        sysctl_file: /etc/sysctl.d/99-custom.conf
        reload: false
        ignoreerrors: true
      register: fs_nr_open_result
    - name: Set fs.file-max
      ansible.builtin.sysctl:
        name: fs.file-max
        value: "5000000"
        state: present
        sysctl_file: /etc/sysctl.d/99-custom.conf
        reload: false
        ignoreerrors: true
      register: fs_file_max_result
    - name: configure DefaultLimitNOFILE in system.conf
      ini_file:
        path: /etc/systemd/system.conf
        section: Manager
        option: DefaultLimitNOFILE
        value: 6500535
        backup: true
    - name: set limits with value check
      lineinfile:
        path: /etc/security/limits.conf
        regexp: '^{{ item.user }}\s+{{ item.type }}\s+nofile\s+.*$'
        line: '{{ item.user }} {{ item.type }} nofile {{ item.value }}'
        state: present
        backup: true
      loop:
        - { user: 'root', type: 'hard', value: '6500536' }
        - { user: 'root', type: 'soft', value: '6500535' }
        - { user: '\*', type: 'soft', value: '40000000' }
        - { user: '\*', type: 'hard', value: '40000000' }
    - name: create deploy user
      user:
        name: deploy
        shell: /bin/bash
        create_home: true
        state: present
    - name: create .ssh directory
      file:
        path: /home/deploy/.ssh
        state: directory
        owner: deploy
        group: deploy
        mode: '0700'
    - name: add public key to authorized_keys
      lineinfile:
        path: /home/deploy/.ssh/authorized_keys
        line: "{{ dev_id_rsa_pub }}"
        state: present
        owner: deploy
        group: deploy
        mode: '600'
        create: true
    - name: set private key from vault
      copy:
        content: "{{ dev_id_rsa }}"
        dest: /home/deploy/.ssh/id_rsa
        owner: deploy
        group: deploy
        mode: '0600'
    - name: set public key from vault
      copy:
        content: "{{ dev_id_rsa_pub }}"
        dest: /home/deploy/.ssh/id_rsa.pub
        owner: deploy
        group: deploy
        mode: '0644'
    - name: set ownership on home directory
      file:
        path: /home/deploy
        owner: deploy
        group: deploy
        state: directory
    - name: create projects_conf directory
      file:
        path: /etc/nginx/projects_conf
        state: directory
        mode: '0755'
    - name: create projects directory
      file:
        path: /etc/nginx/projects
        state: directory
        owner: deploy
        group: deploy
        mode: '0777'
    - name: create panels directory
      file:
        path: /etc/nginx/projects/panels
        state: directory
        owner: deploy
        group: deploy
        mode: '0777'
    - name: create GeoIP directory
      file:
        path: /var/www/server/frontend/shared/runtime/GeoIP
        state: directory
        owner: deploy
        group: deploy
        mode: '0755'
        recurse: true
    - name: check env
      shell: |
        if [ -f /.dockerenv ]; then echo "docker";
        elif command -v systemctl >/dev/null 2>&1; then echo "systemd";
        else echo "other"; fi
      register: env_type
      changed_when: false
    - name: create default.conf placeholder
      copy:
        dest: /etc/nginx/default.conf
        content: "# Placeholder file - update with actual configuration"
        owner: root
        group: root
        mode: '0644'
      ignore_errors: true
    - name: deploy nginx.conf
      copy:
        src: nginx.conf
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root
        mode: '0644'
        backup: true
      register: config_deployed
    - name: validate configuration
      command: nginx -t
      register: config_test
      changed_when: false
      when: config_deployed.changed
    - name: manage nginx service
      when:
        - config_deployed.changed
        - config_test.rc == 0
      block:
        - name: reload systemd nginx
          systemd:
            name: nginx
            state: reloaded
          when: env_type.stdout == "systemd"
        - name: check and reload docker nginx
          when: env_type.stdout == "docker"
          block:
            - name: check if nginx is running in Docker
              shell: pgrep nginx >/dev/null 2>&1 && echo "running" || echo "stopped"
    - name: logrotate is installed
      apt:
        name: logrotate
        state: present
    - name: Create logrotate configuration for Nginx
      copy:
        dest: /etc/logrotate.d/nginx
        content: |
          /var/log/nginx/*.log {
              daily
              missingok
              rotate 30
              compress
              delaycompress
              notifempty
              create 0640 www-data adm
              sharedscripts
              postrotate
                  [ -s /run/nginx.pid ] && kill -USR1 `cat /run/nginx.pid`
              endscript
          }
        owner: root
        group: root
        mode: '0644'
