---
- name: Config Deb11
  hosts: all
  become: true

  tasks:
    - name: Set timezone +0 (UTC)
      ansible.builtin.timezone:
        name: "UTC"
    - name: Remove user debian
      ansible.builtin.user:
        name: debian
        state: absent
        remove: true
