---
- name: Config Deb11
  hosts: all
  become: true

  tasks:
    - name: Set timezone +0 (UTC)
      ansible.builtin.timezone:
        name: Etc/UTC
    - name: Remove user debian
      ansible.builtin.user:
        name: debian
        state: absent
        remove: true
    - name: update apt cache
      ansible.builtin.apt:
        update_cache: true
    - name: Install list of packages
      ansible.builtin.apt:
        pkg:
          - libfreetype6
          - libfreetype6-dev
          - zlib1g
          - zlib1g-dev
          - libxml2
          - libxml2-dev
          - libxslt1-dev
          - libxslt1.1
          - gcc
          - curl
          - make
          - libcurl4-openssl-dev
          - libssl-dev
          - mc
          - wget
          - aptitude
          - unzip
          - htop
          - nload
          - libffi-dev
          - libmariadb-dev
          - default-libmysqlclient-dev
          - mariadb-client
          - gnupg2
          - pkg-config
          - tcl
          - git
          - sendmail
          - openssl
          - python3
          - python3-pip
          - python-setuptools
          - screen
          - ethtool
          - openssl
          - nodejs
          - npm
        state: latest
        update_cache: true
    - name: install nginx latest version
      ansible.builtin.apt:
        name: nginx
        state: latest
    - name: install reqired depend for mysql
      ansible.builtin.apt:
        name:
          - lsb-release
        state: present
        update_cache: true
    - name: add GPG key mysql apt repo
      ansible.builtin.apt_key:
        url: https://repo.mysql.com/RPM-GPG-KEY-mysql-2022
        state: present
    - name: add mysql apt repo
      ansible.builtin.apt_repository:
        repo: "deb http://repo.mysql.com/apt/debian/ {{ ansible_lsb.codename }} mysql-apt-config"
        state: present
        filename: mysql.list
    - name: update apt cach after add repo
      ansible.builtin.apt:
        update_cache: true
    - name: install mysql server
      ansible.builtin.apt:
        name: mysql-server
        state: present
    - name: check my sql sevice
      ansible.builtin.service:
        name: mysql
        state: started
        enabled: true
    - name: set root pass
      ansible.builtin.mysql_user:
        name: root
        host: "{{ item }}"
        password: "{{ mysql_root_password }}"
        login_unix_socket: /var/run/mysld/mysqld.sock
        state: present
        check_implicit_admin: true
      loop:
        - localhost
        - 127.0.0.1
        - '::1'
